{% set name = "hstream" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hstream-{{ version }}.tar.gz
  sha256: 992e8e22e9fc83b6c65224a0264733be2a6983d0d9db8e347fa76e316e46bc6f

build:
  entry_points:
    - hstream = hstream.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.10,<4.0
    - poetry-core
  run:
    - python >=3.10,<4.0
    - cherrypy >=18.9.0,<19.0.0
    - click >=8.1.7,<9.0.0
    - yattag >=1.15.2,<2.0.0
    - ipdb >=0.13.13,<0.14.0
    - markdown >=3.6,<4.0
    - beautifulsoup4 >=4.12,<5.0

test:
  commands:
    - hstream --help

about:
  home: https://github.com/conradbez/hstream
  summary: Create python webapps with ease
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
