{% set name = "hstream" %}
{% set version = "0.0.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hstream-{{ version }}.tar.gz
  sha256: a080208df85af49334e3a5f847bb2815c282558f6e9fea90c003d8711992b7d7

build:
  entry_points:
    - hstream = hstream.runner:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - fastapi >=0.85,<1.dev0
    - jinja2 >=3.1,<4.dev0
    - markdown >=3.4,<4.dev0
    - matplotlib-base
    - python >=3.6
    - python-multipart
    - starlette-context ==0.3.4
    - uvicorn >=0.19,<1.dev0
    - watchfiles >=0.18,<1.dev0
    - yattag >=1.14,<2.dev0

test:
  commands:
    - hstream --help

about:
  home: https://github.com/conradbez/hstream
  summary: Create python webapps with ease
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
