schema_version: 1

context:
  name: hstream
  version: "0.5.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/hstream-${{ version }}.tar.gz
  sha256: 29b9a7440c450fb32d2918ef6bb61070e37fe7faf7d73ae3f9bea782d8947781

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - hstream = hstream.cli:cli

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - poetry-core
  run:
    - python >=${{ python_min }}
    - click >=8.1.7,<9.0.0
    - yattag >=1.15.2,<2.0.0
    - markdown >=3.6,<4.0
    - beautifulsoup4 >=4.12,<5.0
    - django >=5.0.6,<6.0.0

tests:
  - python:
      imports:
        - hstream
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - hstream --help

about:
  summary: Create python webapps with ease
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/conradbez/hstream

extra:
  recipe-maintainers:
    - thewchan
