schema_version: 1

context:
  name: hstream
  version: "0.5.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/hstream-${{ version }}.tar.gz
  sha256: 8d20cc7153370f9f79c193cb5d7bd7ae14d1b22096edd692444ad83c303b007f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - hstream = hstream.cli:cli

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - click >=8.1.7
    - yattag >=1.15.2
    - markdown >=3.6
    - beautifulsoup4 >=4.12
    - django >=5.0.6

tests:
  - python:
      imports:
        - hstream
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - hstream --help

about:
  summary: Create python webapps with ease
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/conradbez/hstream

extra:
  recipe-maintainers:
    - thewchan
