schema_version: 1

context:
  python_min: 3.10
  name: hstream
  version: 0.1.57

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/hstream-${{ version }}.tar.gz
  sha256: 0effc5289e312e8f5882ac33e68a20d051e3a1cb4cdc41f751f4aa195c3887c1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - hstream = hstream.cli:cli

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - poetry-core
  run:
    - python >=${{ python_min }}
    - click >=8.1.7,<9.0.0
    - yattag >=1.15.2,<2.0.0
    - markdown >=3.6,<4.0
    - beautifulsoup4 >=4.12,<5.0
    - django >=5.0.6,<6.0.0

tests:
  - python:
      imports:
        - hstream
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - hstream --help

about:
  summary: Create python webapps with ease
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/conradbez/hstream

extra:
  recipe-maintainers:
    - thewchan
